FROM php:8.2-cli

RUN apt-get update && apt-get install -y \
    git unzip curl libzip-dev zip \
    && docker-php-ext-install zip

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /app
COPY . .

RUN composer install

# Permissions fix
RUN chmod -R 775 storage
RUN chmod -R 775 bootstrap/cache

# Cache fix
RUN php artisan config:clear
RUN php artisan cache:clear
RUN php artisan config:cache

# Run migrations
RUN php artisan migrate --force

EXPOSE 10000

CMD php artisan serve --host=0.0.0.0 --port=10000